<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Tests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DictionaryApp.fsproj" />
    <PackageReference Include="Expecto" Version="9.0.4" />
  </ItemGroup>

</Project>
